//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFAccount
    {
        public EFAccount()
        {
            this.Students = new HashSet<EFStudent>();
        }
    
        public int AccountID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> InstructorID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public decimal Balance { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual EFStudent Student { get; set; }
        public virtual ICollection<EFStudent> Students { get; set; }
    }
}
