//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFClasses
    {
        public EFClasses()
        {
            this.Clocks = new HashSet<EFClock>();
        }
    
        public int ClassID { get; set; }
        public Nullable<int> InstructorID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string Day { get; set; }
        public Nullable<System.TimeSpan> Start_Time { get; set; }
        public Nullable<System.TimeSpan> End_Time { get; set; }
    
        public virtual EFCourse Cours { get; set; }
        public virtual ICollection<EFClock> Clocks { get; set; }
    }
}
