//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFClock
    {
        public int ClockID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> ClockedIn { get; set; }
        public Nullable<bool> Absence { get; set; }
    
        public virtual EFClasses Class { get; set; }
    }
}
