//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFInstructor
    {
        public int InstructorID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int ClassID { get; set; }
        public string Address { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public string StateCode { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public Nullable<int> AccountID { get; set; }
    }
}
