//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFRegistration
    {
        public int StudentID { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> Estimated_Finish_Date { get; set; }
        public Nullable<decimal> Credits { get; set; }
        public int RegistrationID { get; set; }
    
        public virtual EFStudent Student { get; set; }
    }
}
