//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFState
    {
        public EFState()
        {
            this.ZIPCodes = new HashSet<EFZipCode>();
        }
    
        public string StateCode { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<EFZipCode> ZIPCodes { get; set; }
    }
}
