//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFStudent
    {
        public EFStudent()
        {
            this.Accounts = new HashSet<EFAccount>();
            this.Grades = new HashSet<EFGrade>();
            this.Registrations = new HashSet<EFRegistration>();
        }
    
        public int StudentID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public string StateCode { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string Photo { get; set; }
    
        public virtual ICollection<EFAccount> Accounts { get; set; }
        public virtual EFAccount Account { get; set; }
        public virtual ICollection<EFGrade> Grades { get; set; }
        public virtual ICollection<EFRegistration> Registrations { get; set; }
    }
}
